version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bagiratest-backend
    ports:
      - "8081:8080"
    depends_on:
      - db
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bagiratest-frontend
    ports:
      - 3000:3000
  db:
    image: postgres:latest
    container_name: bagiratest-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bagira1234
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
